name: EAS Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (if any)
        run: |
          if [ -f "package.json" ] && grep -q '"test"' package.json; then
            npm test -- --watchAll=false
          else
            echo "No tests found, skipping..."
          fi
      
      - name: Build for preview (PR only)
        if: github.event_name == 'pull_request'
        run: eas build --platform all --profile preview --non-interactive
      
      - name: Build for production (main branch only)
        if: github.ref == 'refs/heads/main'
        run: eas build --platform all --profile production --non-interactive
      
      - name: Submit to app stores (production only)
        if: github.ref == 'refs/heads/main'
        run: |
          # Uncomment when ready for app store deployment
          # eas submit --platform ios --latest
          # eas submit --platform android --latest
          echo "App store submission disabled. Enable when ready for production."

  update:
    name: EAS Update
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish update
        run: eas update --auto
